- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/atsushi/youtubesync/MainActivity.java
- app/src/main/java/com/example/atsushi/youtubesync/SignUpActivity.java
- app/src/main/java/com/example/atsushi/youtubesync/Token.java
resolve #5 
MainActivityが何やってるか意味不明だったので，Room選択 or 生成の役割だけにして，それ以外を切り出した．ただ，SignUp経由で SignInがあるせいで若干キモいことになっているが，ちょっと時間との問題(根本的に抱えてる問題がでかすぎる)ので協議しましょう．
> Refactor main activity

- app/src/main/java/com/example/atsushi/youtubesync/PlayListAdapter.java
- app/src/main/res/layout/play_list_empty_view.xml
- app/src/main/res/values/strings.xml
> プレイリストに動画が入っていない場合に説明文を表示する

- app/src/main/java/com/example/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/example/atsushi/youtubesync/RoomInformationFragment.java
- app/src/main/res/layout/room_information_fragment.xml
- app/src/main/res/values/strings.xml
> ルームキー共有のボタンを作成 

- app/src/main/java/com/example/atsushi/youtubesync/RoomActivity.java
close #38 
チャットが表示されない方も治りました。
> 初回起動時にプレイリストに動画がないことの表示がされない

- app/src/main/java/com/example/atsushi/youtubesync/ChatFragment.java
- app/src/main/java/com/example/atsushi/youtubesync/ChatListAdapter.java
- app/src/main/java/com/example/atsushi/youtubesync/PlayListAdapter.java
- app/src/main/java/com/example/atsushi/youtubesync/PlayListFragment.java
- app/src/main/java/com/example/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/example/atsushi/youtubesync/RoomInformationFragment.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/BaseList.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/ChatList.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/ListInterface.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/PlayList.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/RoomData.java
- app/src/main/java/com/example/atsushi/youtubesync/app_data/RoomDataInterface.java
- app/src/main/res/layout/activity_video.xml
- app/src/main/res/layout/play_list_header.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
close #32
これまで以上にroom activityがぶくぶくしてきたので困ってます。
* プレイリストにまだ動画が残っている場合（動画と動画の間の時間）
* プレーヤー： 次の動画のサムネイルを表示する、再生待機状態
* 動画タイトル表示部：次の動画のタイトルを表示する
* プレイリストにもう曲がない場合
* プレーヤー： 非表示
* 動画タイトル表示部：非表示
> 再生中の動画がない場合の挙動を定義する

- app/src/main/res/layout/chat_fragment.xml
- app/src/main/res/values/colors.xml
> [fix] res/colorにうつした．

- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/activity_sign_up.xml
- app/src/main/res/layout/chat_fragment.xml
- app/src/main/res/layout/play_list_fragment.xml
- app/src/main/res/layout/search_result_video_list_footer.xml
- app/src/main/res/layout/video_list.xml
- app/src/main/res/values/colors.xml
> API非推奨のレイアウトを修正する

- app/src/main/res/values/strings.xml
> シェアボタンのメッセージ変更

- app/src/main/java/com/cyder/atsushi/youtubesync/BaseAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/BaseListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/ChatFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/ChatListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/OnlineUsersAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/PlayListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/PlayListFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomInformationFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/app_data/OnlineUsersList.java
- app/src/main/java/com/cyder/atsushi/youtubesync/app_data/RoomData.java
- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/Room.java
- app/src/main/res/layout/online_users_list_header.xml
- app/src/main/res/layout/online_users_list_item.xml
- app/src/main/res/layout/room_information_fragment.xml
- app/src/main/res/values/strings.xml
close #14
RoomInformationFragment内に記述。
引っ張ったら更新されます。
adapterが増えてきたのでBaseAdapter作って共通部をまとめました。
> オンラインメンバーを表示する

- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/TopActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/channels/RoomChannel.java
- app/src/main/java/com/cyder/atsushi/youtubesync/channels/RoomChannelInterface.java
- app/src/main/res/layout/activity_top.xml
- app/src/main/res/values/strings.xml
close #55
サーバからrejectされたらTopActivityに戻ってsnackbarを表示
> 存在しないルームキーで入室できるバグの修正

- app/src/main/java/com/cyder/atsushi/youtubesync/TopActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/Response.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/HttpRequestsHelper.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/JoinedRooms.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/JoinedRoomsInterface.java
- app/src/main/res/layout/activity_top.xml
- app/src/main/res/layout/room_card.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
close #18
すごい使いやすいアプリになった。
Cardを使いたかったのでaddViewでやってます。
> 最近入室したルームを表示する

- app/build.gradle
ごめん、色々試しているうちにversionCode 2使ったんだ。
タグとかの使い方がわからないマン。
> versionCodeの変更

- app/build.gradle
- app/src/main/java/com/cyder/atsushi/youtubesync/SignUpActivity.java
> 新規登録できないバグ

- app/src/main/java/com/cyder/atsushi/youtubesync/SignInActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/SignUpActivity.java
> ログイン / サインイン時にエラーが起きた際、パスワードのみを消すようにした

- app/src/main/java/com/cyder/atsushi/youtubesync/ChatFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/PlayListFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomFragmentPagerAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomInformationFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/app_data/RoomData.java
close #52
完全に勝利した。
fragmentをちゃんと保存するようにしたのと、諸々の呼び出し場所を調整しました。
> NullPointerExceptionを殺す

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/cyder/atsushi/youtubesync/MainActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/TopActivity.java
- app/src/main/res/values/strings.xml
close #63
http://app.sync-pod.com/room?room_key=[room_key] で自動で入室できるようにした。
http://app.sync-pod.com からプレイストアにリダイレクトするようにします。（TODO）
URL経由でアプリを立ち上げると無駄にAcitivityのスタックがたまったので、 `intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);` で消してます。
> URLからルームへ入れるようにする

- app/src/main/java/com/cyder/atsushi/youtubesync/TopActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/Room.java
- app/src/main/res/layout/room_card.xml
- app/src/main/res/values/strings.xml
> 最近入室したルームの情報追加

- app/src/main/java/com/cyder/atsushi/youtubesync/BaseListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/app_data/BaseList.java
close #86
多分これで落ちなくなったけど、賢い直し方じゃない気もする。
> java.lang.IllegalStateExceptionを殺す

- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomInformationFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/app_data/RoomData.java
clseo #87 
接続が完了した後じゃないとオンラインメンバーに自分が入らないため。
> roominfoを取得するタイミングを変更

- app/src/main/AndroidManifest.xml
resolve #92 
AndroidManifestに追記することで解決しました．
> 画面が回転しないようにした．

- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/BaseResponse.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/CreateRoom.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/HttpRequestsHelper.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/JoinedRooms.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/Room.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/SignIn.java
- app/src/main/java/com/cyder/atsushi/youtubesync/server/SignUp.java
resolve #109 
Responseを動的に差し替えられるようにした．
T.class問題は呼び出し元から送って貰う形で解決した．
> HttpRequestの拡張性をあげる．

- app/src/main/java/com/cyder/atsushi/youtubesync/ChatFormFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/ChatFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/res/layout/activity_room.xml
- app/src/main/res/layout/chat_form_fragment.xml
- app/src/main/res/layout/chat_fragment.xml
フォームがタブの上まで表示されるようにしました。
下からにゅっとでてくるアニメーションは別Issueで対応します。
chatFormAreaをFragment化するか、別クラスに分けるか、どうするのがいいのか悩んでます。
close #41
> キーボードの高さが高いとチャットが快適にできない問題の解決

- app/src/main/java/com/cyder/atsushi/youtubesync/PlayListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/PlayListFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/SearchAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/SearchVideoActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/SearchResponse.java
- app/src/main/java/com/cyder/atsushi/youtubesync/json_data/Video.java
- app/src/main/java/com/cyder/atsushi/youtubesync/youtube/SearchingVideoHelper.java
- app/src/main/res/layout/play_list_header.xml
- app/src/main/res/layout/video_list.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
resolve #15 
ちょっと強引な部分と共通の部分があるのでいずれどうにかしたい．
あとはAPIは自分らで用意したやつを使うようにした．がやっぱりもっさりしてるかも．
> 動画の補足情報を付けた．

- app/src/main/res/layout/play_list_header.xml
- app/src/main/res/layout/video_list.xml
- app/src/main/res/values/colors.xml
> 動画情報周辺のデザイン修正

- app/src/main/java/com/cyder/atsushi/youtubesync/ChatFormFragment.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/java/com/cyder/atsushi/youtubesync/animations/ResizeAnimation.java
- app/src/main/res/values/integers.xml
close #108
close #95
違和感はマシになった気がするけど、完全解決はしてない気もする。
逆にタブと一緒に左右に動かしたほうがいいのかな？
コード的には、48dpが手打ちなところがやばみを感じます。
同時に #95 も解決しました。
> チャットフォームにアニメーションをつける。

- app/src/main/java/com/cyder/atsushi/youtubesync/ChatListAdapter.java
> [update] 時間情報の修正

- app/src/main/res/layout/activity_create_room.xml
- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/layout/activity_sign_up.xml
> キーボードが出現した時に、ボタンを押せなくなる問題を修正

- app/src/main/res/layout/chat_form_fragment.xml
close #118 
入室時に一瞬チャットフォームが表示されることがあったため
> デフォルトの状態でチャットフォームを非表示にした

- app/src/main/res/values/strings.xml
> ルーム共有メッセージを変更

- app/src/main/res/layout/chat_fragment.xml
> チャットフォームの高さがおかしい

- app/src/main/java/com/cyder/atsushi/youtubesync/ChatListAdapter.java
- app/src/main/java/com/cyder/atsushi/youtubesync/RoomActivity.java
- app/src/main/res/values/strings.xml
> ルーム退出時の確認を付ける

- app/src/main/AndroidManifest.xml
close #133
sync-pod://app.com/room でもアプリが開くようにした。
> カスタムURLを追加

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/BaseApplication.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/FragmentComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/FragmentModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/scope/ActivityScope.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/scope/FragmentScope.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/BaseActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/MainActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/base/ActivityViewModel.kt
とりあえずdiとdaggerを使う理由は下を参考にしてください．
Kotlinで書くためにちょいと工夫がいるところがあった．
```  @Suppress("DEPRECATION") ``` してるところあるけど，これはそのうち解決されます(実際にアプリをこいつで動かすようにしたらこれは解決されるぽい)
[参考]
https://qiita.com/takahirom/items/aa9087b075cc9b7249b6
> daggerを使うためのソースコードの設定をした．

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/BaseApplication.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SignInApi.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/Response.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/Room.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/User.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/response/Video.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/BaseActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignInActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
分割しろと言われるので，とりあえずのところまで書いた．
UerReoisutiryはinterfaceになっていて実際の処理はDataの方に書いてる．
ViewModelからはここらのinterfaceの方を呼び出すことで依存を減らす．
あとは，ViewmodelでRepositoryを呼んできて，signin処理をする．
> SignInの流れのうちRepositoryのところまでを書いた．

- app/build.gradle
- app/src/main/resources/log4j.properties
- app/src/test/java/com/cyder/atsushi/youtubesync/server/SignInTest.java
- app/src/test/resources/mappings/login.json
- build.gradle
close #146 
@Kousuke-N ぜひ見てください．
これはとりあえずWireMockという，APIのレスポンスをモックしてくれる奴で作っています．
ノリとしては，このエンドポイントにはこのレスポンスが返るはずという仮定をしたMockをおいておいて，このメソッドが呼ばれるときそのレスポンスを拾えているかみたいな感じでチェックします．
とりあえずでしか書いてないので，まずはSignInのレスポンスを現実のものにピッタリ合わせて書き直してみると良いと思います．
テストの仕方は，
1. Testを書いたクラスを開く
2. Run Testを押す．
3. しばらくすると結果が出る．
これが100%パスになってたらおっけーです．
> SignInでのTestのサンプル

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/CreateRoomActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
- app/src/main/res/layout/activity_create_room.xml
close #163 
#159 がマージされた後にrebaseしてマージ
> roomの作成(UI)

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/MainActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
Top画面を表示する際にスタックをすべて消すようにした
close #178
> ログイン後に戻るボタンを押すと白い画面が出るバグを修正

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
close #157 
だいぶ頑張った（つもり）
エラー系のクラスをどこに書くか悩んでます。
> ログインミスったときのメッセージをいい感じにする

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/request/CreateRoom.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/NetworkModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
- app/src/main/res/layout/activity_room.xml
- app/src/main/res/layout/item_room.xml
- app/src/main/res/values/strings.xml
- build.gradle
+ Close #164 
+ roomを作って入る．
+ `RoomActivity`には `key`を渡してroomに入る，
+ 入れたかどうかはCompletableで返ってくる．
+ `disconnect`の処理はまだしていない．
+ とりあえずroomに入るだけ．
> roomを作る・roomに入る．

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Room.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
ちらちらしてたのを直した． 
Close #186 
変化があるところだけaddするようにした．
> 最近入室した部屋がちらつかないようにした

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignInActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignUpActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SplashActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
> URLから入室できるようにする

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/Exceptions.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/CreateRoomActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignInActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/SignUpActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/TopActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
close #195 
close #190
起動しないバグを修正しました。
あと、Snackbarの初期化をまとめたり、Exceptionをまとめたりしました。
> roomを作るときのエラーハンドリング

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/VideoFragmentViewModel.kt
- app/src/main/res/layout/fragment_video.xml
> 動画のプログレスバーを表示する 

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/BaseActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/CreateRoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignInActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SignUpActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SplashActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/TopActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/VideoFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/WelcomeActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/base/ActivityViewModel.kt
- app/src/main/res/layout/activity_room.xml
* ビデオの表示非表示の切り替え
* 一回バックグラウンドに行ったときの再開処理
TODO
* playlistとの調整
* メモリ解放時のエラー修正
> ビデオの表示非表示の切り替え

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/NetworkModule.kt
> apiのアドレスを変更する

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/api/SyncPodApi.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/ActivityComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserReportDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/UserReportRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/UserReportActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/Navigator.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserReportActivityViewModel.kt
- app/src/main/res/layout/activity_user_report.xml
- app/src/main/res/layout/fragment_roominfo.xml
- app/src/main/res/values/strings.xml
close #171 
もうちょっと上手くやる方法はありそう
> 悪質ユーザー報告フォーム(UI & Logic)

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/VideoDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
>  メモリ解放時にアプリが落ちるバグを修正

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/SearchVideoActivityViewModel.kt
close #233
snackbar出すか悩んだけど、別にいらないと思いました。
> 動画検索フォームがからの時に落ちるバグを修正

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/Data.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApi.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
- app/src/main/res/values/strings.xml
close #213
currentFocusはやっぱりnullになるときがあるらしい
> 強制退出を受けた時に自ら退出する

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/model/Chat.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/ChatRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/adapter/ObservableListAdapter.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFragment.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/Data.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApi.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/SyncPodWsApiImpl.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/mapper/ChatDataMapper.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/websocket/response/Chat.kt
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/item_chat.xml
Close #216 
ひょいってなるアニメーションは別Issueで．
↑はリリースまでにやる？
> チャットを見たり送ったり

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/AppModule.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomDataRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/repository/RoomRepository.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomInfoFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/UserViewModel.kt
> ViewModelからsyncPodWsApiを消し去る

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/di/FragmentComponent.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/util/CustomBinder.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/activity/RoomActivity.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFormFragment.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/ViewHelper.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/helper/animation.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFormFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/RoomActivityViewModel.kt
- app/src/main/res/layout/activity_room.xml
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/fragment_chat_form.xml
close #235 
チャットフォームを下からひょいってするようにしました。
> チャットフォームをフラグメント化する

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/fragment/ChatFragment.kt
- app/src/main/kotlin/com/cyder/atsushi/youtubesync/viewmodel/ChatFragmentViewModel.kt
- app/src/main/res/layout/fragment_chat.xml
close #239 
* キーボードが出た時もちゃんとスクロール位置が固定されるようにした
* チャットが追加された時に全体をロードしないようにした
* 一番下までスクロールされているときのみ、チャットが追加された際に自動スクロールされるようにした
> チャットのスクロールを固定する

- app/src/main/kotlin/com/cyder/atsushi/youtubesync/view/components/WithoutKeyEventViewPager.kt
- app/src/main/res/layout/activity_room.xml
> キーボードの左右キーでタブが移動しないようにした

- app/proguard-rules.pro
Close #245 
なんかワーニングでてビルドコケるっぽいけどignoreしていいっぽ
これで署名なしではビルド通るので署名てきとうにほげってビルドしたらいいと思います．
> productionbuildでコケるのを直す

- app/build.gradle
- app/src/main/kotlin/com/cyder/android/syncpod/view/activity/SearchVideoActivity.kt
- app/src/main/kotlin/com/cyder/android/syncpod/view/activity/TopActivity.kt
- app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/ChatFragment.kt
- app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/PlayListFragment.kt
- app/src/main/kotlin/com/cyder/android/syncpod/view/fragment/RoomInfoFragment.kt
> lib versionを上げる

- app/src/main/kotlin/com/cyder/android/syncpod/di/NetworkModule.kt
> roomに入れないバグを倒す

- app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/SearchVideoActivityViewModel.kt
- app/src/main/res/layout/activity_search_video.xml
Close #254 
actionIdみなくても検索大丈夫だったというオチ
> 検索できるようにする

- app/src/main/kotlin/com/cyder/android/syncpod/view/activity/CreateRoomActivity.kt
- app/src/main/kotlin/com/cyder/android/syncpod/viewmodel/CreateRoomActivityViewModel.kt
- app/src/main/res/layout/activity_create_room.xml
- app/src/main/res/layout/spinner_item_with_description.xml
- app/src/main/res/values/strings.xml
close #271
あとは @chigichan24 に任せた
> 公開ルーム設定デザイン
